const mongoose=require('mongoose');
const productSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    price:{
        type:Number,
        required:true,
        default:0.0
    },
    description:{
        type:String,
        required:true,
    },
    ratings:{
        type:Number,
        default:0
    },
    images:[
        {
        type:Array
        }
    ],
    category:{
            type:String,
            required:true,
            enum:{
                values:[
                    'Electronics',
                    'cameras',
                    'laptop',
                    'Accessories',
                    'Food',
                    'Books',
                    'Sports',
                    'Clothes',
                    'Beauty',
                    'Health'
                ],
                message:'Please select category for product'
            }
    },
    seller:{
        type:String,
        required:true
    },
    stock:{
        type:Number,
        required:true,
        default:0
    },
    numOfReviews:{
        type:Number,
        default:0
    },
    reviews:[
        {
            name:{
                type:String,
                required:true
            },
            rating:{
                type:Number,
                required:true
            },
            comment:{
                type:String,
                required:true
            }
        }
    ],
    createdAt:{
        type:Date,
        default:Date.now
    }
})
module.exports=mongoose.model('Product',productSchema)